
FROM node:latest AS builder

WORKDIR /app

COPY . /app

RUN yarn install && yarn web:build:prod

FROM nginx:latest

RUN sed -i 's/listen  *80;/listen 8080;/g' /etc/nginx/conf.d/default.conf
EXPOSE 8080

COPY --from=builder /app/web/.webpack /usr/share/nginx/html
